# Generated by Django 5.1.1 on 2024-09-26 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lo_profile', '0003_alter_profile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkedIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('position', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('avatar', models.URLField(blank=True, null=True)),
                ('connections', models.CharField(blank=True, max_length=255, null=True)),
                ('connect_level', models.CharField(blank=True, max_length=255, null=True)),
                ('time_in_role', models.CharField(blank=True, max_length=255, null=True)),
                ('activity', models.TextField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
