# Generated by Django 5.1.1 on 2024-09-26 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lo_profile', '0004_linkedin_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkedin',
            name='avatar',
            field=models.URLField(blank=True, max_length=2083, null=True),
        ),
        migrations.AlterField(
            model_name='linkedin',
            name='url',
            field=models.URLField(blank=True, max_length=2083, null=True),
        ),
    ]
