# Generated by Django 5.1.1 on 2024-09-29 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lo_profile', '0006_contact_alter_linkedin_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='CONTACT_MOBILE',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='CONTACT_PHONE',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='FLOORAREA',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=255, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='PHONE',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='POSTCODE',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='POST_CD',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='SALUTATION',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='SITE_AREA',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=255, null=True),
        ),
    ]
