# Generated by Django 5.1.1 on 2024-10-01 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lo_profile', '0007_alter_contact_contact_mobile_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='CONTACT_LINKEDIN_URL',
            new_name='LINKEDIN_URL',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='CONTACT_MOBILE',
            new_name='MOBILE',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='CONTACT',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='CONTACT_ID',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='CONTACT_PHONE',
        ),
        migrations.AddField(
            model_name='contact',
            name='SHOULD_UPDATE',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
