# Generated by Django 5.1.1 on 2024-10-01 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lo_profile', '0009_rename_addr_1_contact_addr_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='activity',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='avatar',
            field=models.URLField(blank=True, max_length=2083, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='connect_level',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='connections',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='time_in_role',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
