# Generated by Django 5.1.1 on 2024-10-15 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lo_profile', '0010_contact_activity_contact_avatar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='heading',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='project_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='projectid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
