apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: go-leadopt
build:
  artifacts:
  - image: go-leadopt-backend
    context: backend/src
    docker:
      dockerfile: Dockerfile
  - image: go-leadopt-frontend
    context: frontend/src
    docker:
      dockerfile: Dockerfile
manifests:
  rawYaml:
  - frontend/k8s/*.yaml
  helm:
    releases:
    - name: backend
      chartPath: backend
      valuesFiles:
      - backend/values.yaml
      version: 0.1.0

profiles:
  - name: mix-deploy
    patches:
     - op: remove
       path: /manifests/helm
    deploy:
      helm:
        releases:
        - name: backend
          chartPath: backend
          valuesFiles:
          - backend/values.yaml
          version: 0.1.0
