apiVersion: v1
kind: Service
metadata:
  name: go-leadopt-frontend
  labels:
    app: frontend
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
  - protocol: TCP
    port: 8080
    targetPort: http-server
    nodePort: 30001
