apiVersion: v1
kind: Service
metadata:
  name: go-leadopt-mongodb
  labels:
    app: leadopt
    tier: db
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
      nodePort: 30002
  selector:
    app: leadopt
    tier: db
