apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service}}
  labels:
    app: {{ .Values.service}}
spec:
  type: NodePort
  selector:
    app: {{ .Values.service}}
  ports:
    - protocol: TCP
      port: 8081
      targetPort: http-server
      nodePort: 30000
