apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service}}
  labels:
    app: {{ .Values.service}}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.service}}
  ports:
    - port: 8081
      targetPort: http-server
